#!/bin/bash
#SBATCH --output=logs/%x_%j.log
#SBATCH --error=logs/%x_%j.err
#SBATCH --exclusive
#SBATCH --time=24:00:00
#SBATCH --partition=tupi
#SBATCH --nodelist=tupi6

set -euo pipefail

# -------------------------
# Required variables
# -------------------------
: "${RUN_NAME:?RUN_NAME not set}"
: "${RUN_INDEX:?RUN_INDEX not set}"
: "${MODEL_NAME:?MODEL_NAME not set}"
: "${DATASET_PREFIX:?DATASET_PREFIX not set}"
: "${TRAIN_VARIANT:?TRAIN_VARIANT not set}"
: "${CONFIG_FILE:?CONFIG_FILE not set}"
: "${DATA_PATH:?DATA_PATH not set}"
: "${BATCH_SIZE:?BATCH_SIZE not set}"
: "${EPOCHS_PER_FILE:?EPOCHS_PER_FILE not set}"
: "${SEED:?SEED not set}"
: "${TRAINED_MODELS_DIR:?TRAINED_MODELS_DIR not set}"
: "${DARSHAN_ROOT:?DARSHAN_ROOT not set}"
: "${DARSHAN_LOGDIR:?DARSHAN_LOGDIR not set}"
: "${CONDA_ENV_PATH:?CONDA_ENV_PATH not set}"

echo "🧪 Starting training run ${RUN_INDEX} for ${MODEL_NAME}"
echo "🔎 Darshan log dir: ${DARSHAN_LOGDIR}"
echo "📂 Data path: ${DATA_PATH}"

# -------------------------
# Environment
# -------------------------
source ~/miniconda3/etc/profile.d/conda.sh
conda activate "${CONDA_ENV_PATH}"

# Ensure Conda's library path is exposed (Crucial for PINN/cuDNN matching)
export LD_LIBRARY_PATH="$CONDA_PREFIX/lib:${LD_LIBRARY_PATH:-}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"

cd /scratch/aadsilva/erad-2026/PDEBench/pdebench/models
mkdir -p "${TRAINED_MODELS_DIR}"

# -------------------------
# Darshan Setup
# -------------------------
export LD_LIBRARY_PATH="$DARSHAN_ROOT/lib:${LD_LIBRARY_PATH:-}"
export DARSHAN_LOGDIR="${DARSHAN_LOGDIR}"
export DARSHAN_ENABLE_NONMPI=1
export DXT_ENABLE_IO_TRACE=1
export LD_PRELOAD="$DARSHAN_ROOT/lib/libdarshan.so"
export DARSHAN_LOG_HINTS="jobid=${SLURM_JOB_ID}_run${RUN_INDEX}"

# -------------------------
# Dataset discovery
# -------------------------
mapfile -t DATAFILES < <(
  ls "${DATA_PATH}/${DATASET_PREFIX}"*.h5 \
     "${DATA_PATH}/${DATASET_PREFIX}"*.hdf5 2>/dev/null | sort
)

if [[ ${#DATAFILES[@]} -eq 0 ]]; then
  echo "❌ No data files found in ${DATA_PATH} with prefix ${DATASET_PREFIX}"
  exit 1
fi

# Apply the variant-specific script to ALL models, including PINN
TRAIN_SCRIPT="train_models_forward_${TRAIN_VARIANT}.py"

if [[ ! -f "${TRAIN_SCRIPT}" ]]; then
    echo "❌ Training script not found: ${TRAIN_SCRIPT}"
    exit 1
fi

echo "📄 Training script  : ${TRAIN_SCRIPT}"

# -------------------------
# Independent Training Loop
# -------------------------
for (( i=0; i<${#DATAFILES[@]}; i++ )); do
    FULL_PATH="${DATAFILES[$i]}"
    FILENAME="$(basename "${FULL_PATH}")"
    BASE_NAME="${FILENAME%.*}" 
    
    echo "---------------------------------------------------"
    echo "🔄 Training Independent Model for: ${FILENAME}"
    echo "---------------------------------------------------"

    if [[ "${MODEL_NAME}" == "PINN" ]]; then
        # PINN Argument Structure
        python "${TRAIN_SCRIPT}" \
            "+args=${CONFIG_FILE}" \
            "++args.model_name=${MODEL_NAME}" \
            "++args.root_path=${DATA_PATH}" \
            "++args.seed=${SEED}" \
            "++args.filename=${FILENAME}" \
            "++args.epochs=${EPOCHS_PER_FILE}"
    else
        # FNO & Unet Argument Structure
        python "${TRAIN_SCRIPT}" \
            "+args=${CONFIG_FILE}" \
            "++args.model_name=${MODEL_NAME}" \
            "++args.data_path=${DATA_PATH}" \
            "++args.batch_size=${BATCH_SIZE}" \
            "++args.filename=${FILENAME}" \
            "++args.epochs=${EPOCHS_PER_FILE}" \
            "++args.if_training=true" \
            "++args.continue_training=false"
    fi

    # -------------------------
    # Artifact Capture & Rename
    # -------------------------
    TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
    
    # 1. Capture .pt Model
    GENERATED_MODEL=$(ls -t *.pt 2>/dev/null | head -n 1 || true)
    if [[ -n "${GENERATED_MODEL}" && -f "${GENERATED_MODEL}" ]]; then
        FINAL_NAME="${MODEL_NAME}_${BASE_NAME}_${TIMESTAMP}_Run${RUN_INDEX}.pt"
        mv "${GENERATED_MODEL}" "${TRAINED_MODELS_DIR}/${FINAL_NAME}"
        echo "✅ Model saved: ${FINAL_NAME}"
    else
        echo "⚠️ Warning: No .pt file found after training ${FILENAME}"
    fi

    # 2. Capture .pickle (Generated by PINN evaluations)
    GENERATED_PICKLE=$(ls -t *.pickle 2>/dev/null | head -n 1 || true)
    if [[ -n "${GENERATED_PICKLE}" && -f "${GENERATED_PICKLE}" ]]; then
        FINAL_PICKLE="${MODEL_NAME}_${BASE_NAME}_${TIMESTAMP}_Run${RUN_INDEX}.pickle"
        mv "${GENERATED_PICKLE}" "${TRAINED_MODELS_DIR}/${FINAL_PICKLE}"
        echo "✅ Pickle saved: ${FINAL_PICKLE}"
    fi

    # 3. Capture .png (Generated by PINN evaluations)
    GENERATED_PNG=$(ls -t *.png 2>/dev/null | head -n 1 || true)
    if [[ -n "${GENERATED_PNG}" && -f "${GENERATED_PNG}" ]]; then
        FINAL_PNG="${MODEL_NAME}_${BASE_NAME}_${TIMESTAMP}_Run${RUN_INDEX}.png"
        mv "${GENERATED_PNG}" "${TRAINED_MODELS_DIR}/${FINAL_PNG}"
        echo "✅ PNG saved: ${FINAL_PNG}"
    fi
    
    # Cleanup any leftovers
    rm -f *.pickle *.png
done

echo "✅ All independent trainings completed for Run ${RUN_INDEX}"